#!/bin/bash -l

#SBATCH --partition=shortrun_small
#SBATCH --nodes=1
#SBATCH --time=1-12:00:00
#SBATCH --job-name=DEM_init
#SBATCH --ntasks-per-node=16


#working_dir='PWD'
#cd $working_dir

module load mpi/openmpi/1.10.6/gcc intel-studio-2020 comp/gcc/6.3.0 comp/cmake/3.7.2 lib/flex/2.6.4 lib/bison/3.0.4 lib/scotch/6.3.0 lib/vtk/6.3 lib/boost/1.63.0/intel

mpirun -np 16 ~/LIGGGHTS/LIGGGHTS-iPAT/src-build/liggghts -in in.liggghts_init
